-- ============================================
-- PRESET QUIZZES
-- ============================================

-- Add preset_id to training_sessions to link a session to a preset quiz
alter table training_sessions add column preset_id uuid references sop_presets(id) on delete set null;
create index idx_training_sessions_preset on training_sessions(preset_id);

-- Template questions for each preset (pre-generated by LLM)
create table sop_preset_questions (
  id uuid primary key default gen_random_uuid(),
  preset_id uuid not null references sop_presets(id) on delete cascade,
  sop_id uuid not null references sops(id) on delete cascade,
  question_number integer not null,
  question_text text not null,
  question_type question_type not null,
  options jsonb not null,
  correct_answer text not null,
  explanation text not null,
  related_step_id uuid references sop_steps(id) on delete set null,
  created_at timestamptz not null default now()
);

create index idx_sop_preset_questions_preset on sop_preset_questions(preset_id);
create index idx_sop_preset_questions_sop on sop_preset_questions(sop_id);

-- ROW LEVEL SECURITY

alter table sop_preset_questions enable row level security;

create policy "Staff can view questions for published presets"
  on sop_preset_questions for select using (
    exists (
      select 1 from sop_presets
      where sop_presets.id = sop_preset_questions.preset_id
        and (sop_presets.status = 'published' or is_admin())
    )
  );

create policy "Admins can manage preset questions"
  on sop_preset_questions for all using (is_admin());
